### ISSUE TITLE
Sensors don't log switching to inactive mode

### ISSUE THREAD

**Issue by Benjamin-Lee** [MechWolf/MechWolf#31]
```yaml
log:
- device_id: test
  procedure:
    params:
      rate: 5 Hz
    time: 5.0
  protocol_id: 503283cc-7a96-11e8-86b8-acbc32c766d9
  success: true
  timestamp: 1530164687.28394
- device_id: test
  procedure:
    params:
      rate: 0 Hz
    time: 20.0
  protocol_id: 503283cc-7a96-11e8-86b8-acbc32c766d9
  success: true
  timestamp: 1530164697.0985222
- device_id: test
  procedure:
    params:
      rate: 5 Hz
    time: 15.0
  protocol_id: 503283cc-7a96-11e8-86b8-acbc32c766d9
  success: true
  timestamp: 1530164697.2990599
protocol:
  test:
  - params:
      rate: 5 Hz
    time: 5.0
  - params:
      rate: 0 Hz
    time: 10.0
  - params:
      rate: 5 Hz
    time: 15.0
  - params:
      rate: 0 Hz
    time: 20.0
```
